Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,11 +20,18 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      # TODO: Remove this step
+      - name: Fail the pipeline
+        run: |
+          echo "This step will fail now."
+          exit 1
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
           aws-region: ${{ env.AWS_REGION }}
+        
 
       - name: Login to Amazon ECR
         id: login-ecr
